// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlD-mKU_zkZkptYfYBeOPYYIrIDe3vSWE',
    appId: '1:692969991190:web:ed37d59a267fd6fbc49937',
    messagingSenderId: '692969991190',
    projectId: 'newchat-a9d01',
    authDomain: 'newchat-a9d01.firebaseapp.com',
    storageBucket: 'newchat-a9d01.appspot.com',
    measurementId: 'G-SQ7VSXR4HY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCKAa75LRCR4zSi5WGYO2cONp6GZq-Pa0',
    appId: '1:692969991190:android:04b877b1c71a75c7c49937',
    messagingSenderId: '692969991190',
    projectId: 'newchat-a9d01',
    storageBucket: 'newchat-a9d01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkQuPB0D_-3JyaIuoICVhVmfgzrfKmC-Y',
    appId: '1:692969991190:ios:7bb040284eda2ea4c49937',
    messagingSenderId: '692969991190',
    projectId: 'newchat-a9d01',
    storageBucket: 'newchat-a9d01.appspot.com',
    iosClientId: '692969991190-rpod8k897ale57b7gfm0cbb2ql8fokuh.apps.googleusercontent.com',
    iosBundleId: 'com.example.newchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkQuPB0D_-3JyaIuoICVhVmfgzrfKmC-Y',
    appId: '1:692969991190:ios:3ed00c6cab8aba43c49937',
    messagingSenderId: '692969991190',
    projectId: 'newchat-a9d01',
    storageBucket: 'newchat-a9d01.appspot.com',
    iosClientId: '692969991190-j6irj06ji86voeeufipsv5g0dppkaum5.apps.googleusercontent.com',
    iosBundleId: 'com.example.newchat.RunnerTests',
  );
}
